# NumPy Exercise 1

In [2]:
import numpy as np

### NumPy

In [19]:
# 1 - Create a 1 x 12 numpy array called 'X'
X = [x for x in range(1,13)]
X = np.array(X)

In [20]:
# 2 - Print the dtype of 'X'
X.dtype

dtype('int64')

In [21]:
# 3 - Convert the dtype of 'X' to float
# Make sure to reassign
X = X.astype(float)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.])

In [29]:
# 4 reshape 'X' to be 3 x 4
X = X.reshape((3,4))
print(X)

[[ 1.  2.  3.  4.]
 [ 5.  6.  7.  8.]
 [ 9. 10. 11. 12.]]


In [30]:
# 5 - Print the shape of 'X'
X.shape

(3, 4)

In [31]:
# 6 - Flatten 'X' using either '.flatten()' or '.ravel()'
X.ravel()

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.])

In [32]:
# 7 - Use broadcasting to normalize 'X'
X = X / X.max()
X

array([[0.08333333, 0.16666667, 0.25      , 0.33333333],
       [0.41666667, 0.5       , 0.58333333, 0.66666667],
       [0.75      , 0.83333333, 0.91666667, 1.        ]])